name: manticora
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  archive: ^4.0.9
  camera: ^0.12.0+2
  file_picker: ^12.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_mlkit_text_recognition: ^0.17.1
  image: ^4.9.2
  image_picker: ^1.2.3
  intl: ^0.20.3
  local_auth: ^3.0.2
  path: ^1.9.1
  path_provider: ^2.1.6
  pdf: ^3.13.0
  permission_handler: ^13.0.1
  printing: ^5.15.0
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  sqflite: ^2.4.3
  syncfusion_flutter_pdf: ^34.2.5
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
